// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhPsn5Bz2zVoeXsTXepindvtrahCMuhP4',
    appId: '1:271989742726:web:314f625c4466a413e7c507',
    messagingSenderId: '271989742726',
    projectId: 'readersapp-581ae',
    authDomain: 'readersapp-581ae.firebaseapp.com',
    storageBucket: 'readersapp-581ae.appspot.com',
    measurementId: 'G-XYN7NSNH0N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwTgAbHz3Wk5Jr2bbw4Rx9IytSg7hO8xE',
    appId: '1:271989742726:android:b015f248d265adcce7c507',
    messagingSenderId: '271989742726',
    projectId: 'readersapp-581ae',
    storageBucket: 'readersapp-581ae.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcdfewNb0uEb16CqJ2DD3rAn4PTMd4OmA',
    appId: '1:271989742726:ios:0231e3a4b340dc70e7c507',
    messagingSenderId: '271989742726',
    projectId: 'readersapp-581ae',
    storageBucket: 'readersapp-581ae.appspot.com',
    iosClientId: '271989742726-v4b80nuonnjv5vh7jclme87anrn3gcg9.apps.googleusercontent.com',
    iosBundleId: 'com.example.richdadpoordad',
  );
}
